### PR TITLE
update to uglify-js 2.3.6 to git rid of npm warning during install

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
Would you like to be added as a collaborator on this repository?

**Comment by ralphtheninja** [comment]
@ForbesLindesay Sure why not! :)

**Comment by ForbesLindesay** [comment]
Cool, you're added. Please follow these rules:

1. never commit directly to master unless you're only editing documentation, or you're in the process of cutting a new release.
2. never merge your own pull request unless it's had no comments from any collaborators for at least 24 hours.
3. If you cut a new release, make sure you update History.md and follow [semver](http://semver.org/) when updating the version number.

If you let me know your npm username I'll add you as an owner so you can release new versions :)

**Comment by ralphtheninja** [comment]
It's ralphtheninja. Thanks!

**Comment by ForbesLindesay** [comment]
Thanks. I've added you as an owner :)

**Pull request merged**
